version: "3.8"

services:
  db:
    container_name: backend
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: backend
    volumes:
      - ./mongo:/data/db
